# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-U-ZMQ59J9aCYRZHH430zunB8LCm-6U
"""

m=1
while m!=0:
  print("""
-----------------------------
CONCERTA CELULAR DA PRINCIPAL
-INFORME SEU INTERESSE-
1- CONSERTA APARELHO
2- USUÁRIO
3- LOJA
4- RELATÓRIO
0- SAIR
-----------------------------
  """)
  m=input(" ")

  if m == "1":

   print("""
-----------------------------
   INFORMAÇÃO DO APARELHO
-----------------------------
1° INFORME O NOME DO SEU APARELHO
2° INFORME O PROBLEMA DO SEU APARELHO
   """)

   aparelho=input("NOME DO APARELHO: ")
   problema=input("PROBLEMA DO APARELHO: ")

  elif m== "2" :
    print("""
-----------------------------
         USUARIO
-----------------------------
1- CADASTRAR USUARIO
2- DELETAR USUARIO
3- ATUALIZAR USUARIO
0- SAIR
    """)
    usuario=input(" ")

    if usuario== "1":
      print("""
-----------------------------
    CADASTRAR USUARIO
-----------------------------
1° INFORME SEU NOME
2° E-MAIL PARA CONTATO
3° SEU CPF
4° (OPCIONAL) TELEFONE DE AMIGO PARA CONTATO
      """)

    nome=input("NOME: ")
    email=input("E-MAIL: ")
    cpf=input("CPF: ")
    perm=input("DESEJA ADICIONAR TELEFONE DE AMIGO? (S/N)")
    if perm == "S":
     tele=input("TELEFONE DE AMIGO: ")

  elif m == "3":
   print("""
-----------------------------
           LOJA
-----------------------------
1- CELULAR Á VENDA
2- APA
  """)

